# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 3, 7, 17, 47, 23, 691107, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
