# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20160320_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
